spring:
  application:
    name: application
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
  data:
      redis:
        host: localhost
        port: 6379


mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    default-statement-timeout: 25000
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    aggressive-lazy-loading: false

server:
  port: 18001